###  SpaCy is a library for Natural Language Processing (NLP). It allows you to analyze and understand text with Python.
tokenization, POS tagging, lemmatization, named entity recognition, dependency parsing

In [1]:
import spacy 
import pandas as pd

python -m spacy download en_core_web_sm

loads a small English model that comes with vocabulary, grammar rules, and statistical 
patterns.

In [2]:
nlp=spacy.load('en_core_web_sm')

In [ ]:
text = "Apple is looking at buying a startup in London for $1 billion."
doc=nlp(text)
for token in doc:
    print(token.text,token.pos_,token.lemma_)

Apple PROPN Apple
is AUX be
looking VERB look
at ADP at
buying VERB buy
a DET a
startup NOUN startup
in ADP in
London PROPN London
for ADP for
$ SYM $
1 NUM 1
billion NUM billion
. PUNCT .

In [7]:
df=pd.DataFrame(columns=['token','pos_tag'])
for token in doc:
    df=pd.concat([df,pd.DataFrame.from_records([{'token':token.text,'pos_tag':token.pos_}])],ignore_index=True)

In [8]:
df.head(5)

     token pos_tag
0    Apple   PROPN
1       is     AUX
2  looking    VERB
3       at     ADP
4   buying    VERB

In [ ]:
ts = (
    df.groupby(['token', 'pos_tag'])
      .size()
      .reset_index(name='counts')
      .sort_values(by='counts', ascending=False)
)
ts

      token pos_tag  counts
0         $     SYM       1
1         .   PUNCT       1
2         1     NUM       1
3     Apple   PROPN       1
4    London   PROPN       1
5         a     DET       1
6        at     ADP       1
7   billion     NUM       1
8    buying    VERB       1
9       for     ADP       1
10       in     ADP       1
11       is     AUX       1
12  looking    VERB       1
13  startup    NOUN       1