In [1]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.corpus import stopwords
import pandas as pd

In [4]:
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [5]:
df=pd.read_csv('tripadvisor-hotel-reviews.csv')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Review  109 non-null    object
 1   Rating  109 non-null    int64
dtypes: int64(1), object(1)
memory usage: 1.8+ KB

In [8]:
df.head()

                                              Review  Rating
0  nice hotel expensive parking got good deal sta...       4
1  ok nothing special charge diamond member hilto...       2
2  nice rooms not 4* experience hotel monaco seat...       3
3  unique, great stay, wonderful time hotel monac...       5
4  great stay great stay, went seahawk game aweso...       5

In [10]:
df['Review_lower']=df['Review'].str.lower()
df.head(5)

,Review,Rating,Review_lower
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso..."

In [14]:
en_stopwords=stopwords.words('english')
en_stopwords.remove("not")
df['Review_lower']=df['Review_lower'].apply(lambda x: " ".join(word for word in x.split() if word not in en_stopwords))

In [17]:
import re
df['Review_lower']=df.apply(lambda x: re.sub(r"[^\w\s]","",x['Review_lower']),axis=1)

In [21]:
df['Review_lower'] = df.apply(
lambda x: word_tokenize(x['Review_lower']), axis=1)

In [22]:
ps = PorterStemmer()
df["Review_lower"] = df["Review_lower"].apply(lambda tokens: [ps.stem(token) for
token in tokens])

In [23]:
lemmatizer = WordNetLemmatizer()
df["Review_lower"] = df["Review_lower"].apply(lambda tokens:
[lemmatizer.lemmatize(token) for token in tokens])

In [24]:
tokens_clean = sum(df['Review_lower'], [])

In [25]:
unigrams = pd.Series(nltk.ngrams(tokens_clean, 1)).value_counts()

In [26]:
bigrams = pd.Series(nltk.ngrams(tokens_clean, 2)).value_counts()

In [27]:
ngrams_4 = pd.Series(nltk.ngrams(tokens_clean, 4)).value_counts()